version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./datasources:/etc/grafana/provisioning/datasources

  mysqlExporter:
    image: prom/mysqld-exporter:v0.13.0
    container_name: mysql-exporter
    environment:
      DATA_SOURCE_NAME: "root4:root@(159.89.161.237:3306)/fineract_default"
    ports:
      - "9104:9104"


#host.docker.internal:3306